### ISSUE TITLE
symbol match URL is incorrect

### ISSUE THREAD

**Issue by chrismwendt** [bobheadxi/raycast-sourcegraph#6]
With this query: `repo:github.com/sourcegraph/sourcegraph@rockskip-symbols type:symbol queryBlobs`

<img width="752" alt="CleanShot 2022-02-15 at 20 21 35@2x" src="https://user-images.githubusercontent.com/1387653/154190031-a64acb14-7542-4d56-8fff-3d7144dbdd5a.png">

After I hit enter, I get taken to https://sourcegraph.com/github.com/sourcegraph/sourcegraph@rockskip-symbols/-/blob/enterprise/internal/rockskip/lib.go/github.com/sourcegraph/sourcegraph@rockskip-symbols/-/blob/enterprise/internal/rockskip/lib.go#L918:6-918:16

<img width="1065" alt="CleanShot 2022-02-15 at 20 21 55@2x" src="https://user-images.githubusercontent.com/1387653/154190051-cda735f8-acb4-4968-a477-8bfbdb3ad1af.png">

**Comment by bobheadxi** [comment]
Thanks for spotting this @chrismwendt ! I've fixed this in https://github.com/bobheadxi/raycast-sourcegraph/pull/7 and opened a PR to make the update available from the Raycast store: https://github.com/raycast/extensions/pull/919
