### ISSUE TITLE
improve validation and error messages for self-hosted config

### ISSUE THREAD

**Issue by bobheadxi** [bobheadxi/raycast-sourcegraph#8]
Looks like when a non-auth error happens, `JSON.stringify` prints nothing - this was caused by a trailing slash, can improve validation on that too and maybe cleaning

https://sourcegraph.com/github.com/bobheadxi/raycast-sourcegraph/-/blob/src/hooks/checkAuthEffect.tsx?L18-28

**Comment by unknwon** [comment]
This bug is non-blocking and conceptually it should be a one-liner trimming... Please assign me and let's see if I can work this out 😁 Also interested in developing more Raycast extensions myself so this would be a good start!

**Comment by bobheadxi** [comment]
There's a bare-bones guide in https://github.com/bobheadxi/raycast-sourcegraph/blob/main/CONTRIBUTING.md to get you started!

**Comment by unknwon** [comment]
Here you go 🤣 https://github.com/bobheadxi/raycast-sourcegraph/pull/12
